INSERT INTO stocks.instruments (ticker, stock_market, country, name) VALUES ('SPY', 'XNYS', 'US', 'S&P500')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf (ticker, market_cap) VALUES ('SPY', NULL) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MMM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AOS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ABT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ABBV')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ABMD')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ACN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ATVI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ADBE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AAP')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AMD')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AES')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AFL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'A')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'APD')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AKAM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ALK')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ALB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ARE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ALXN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ALGN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ALLE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'LNT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ALL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'GOOGL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'GOOG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AMZN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AMCR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AEE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AAL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AEP')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AXP')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AIG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AMT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AWK')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AMP')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ABC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AME')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AMGN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'APH')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ADI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ANSS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ANTM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AON')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'APA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AAPL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AMAT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'APTV')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ADM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ANET')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AJG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AIZ')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'T')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ATO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ADSK')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ADP')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AZO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AVB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AVY')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BKR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BLL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BAC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BAX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BDX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BRK.B')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BBY')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BIO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BIIB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BLK')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BWA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BXP')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BSX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BMY')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'AVGO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BF.B')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CHRW')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'COG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CDNS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CZR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CPB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'COF')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CAH')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'KMX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CCL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CTLT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CAT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CBOE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CBRE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CDW')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CNC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CNP')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CERN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CF')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SCHW')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CHTR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CVX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CMG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CHD')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CINF')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CTAS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CSCO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'C')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CFG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CTXS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CME')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CMS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'KO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CTSH')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CMCSA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CMA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CAG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'COP')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ED')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'STZ')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CPRT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'GLW')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'COST')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CCI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CSX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CMI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CVS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DHI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DHR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DRI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DVA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DAL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'XRAY')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DVN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DXCM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FANG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DLR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DFS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DISCA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DISCK')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DISH')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DLTR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'D')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DPZ')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DOV')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DOW')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DTE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DUK')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DRE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DD')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'EMN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ETN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'EBAY')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ECL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'EIX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'EW')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'EA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'EMR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ENPH')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ETR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'EOG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'EFX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'EQIX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'EQR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ESS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'EL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ETSY')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'RE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ES')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'EXC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'EXPE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'EXPD')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'EXR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'XOM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FFIV')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FAST')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FRT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FDX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FIS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FITB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FRC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FISV')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FLT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FLIR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FMC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'F')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FTNT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FBHS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FOXA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FOX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BEN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'FCX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'GPS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'GRMN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'IT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'GNRC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'GD')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'GE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'GIS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'GM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'GPC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'GILD')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'GPN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'GS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'GWW')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HAL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HBI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HIG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HAS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HCA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HSIC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HES')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HPE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HLT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HFC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HOLX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HD')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HON')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HRL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HST')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HPQ')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HUM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HBAN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HII')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'IEX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'IDXX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ITW')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ILMN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'INCY')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'IR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'INTC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ICE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'IBM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'IFF')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'IP')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'IPG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'INTU')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ISRG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'IVZ')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'IPGP')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'IRM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'JBHT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'JKHY')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SJM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'JNJ')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'JCI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'JPM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'JNPR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'KSU')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'K')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'KEY')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'KEYS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'KMB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'KIM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'KMI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'KLAC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'KHC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'KR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'LB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'LH')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'LRCX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'LVS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'LEG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'LDOS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'LEN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'LLY')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'LNC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'LYV')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'LKQ')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'LMT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'L')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'LOW')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'LYB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MTB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MRO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MPC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MKTX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MAR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MMC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MLM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MAS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MXIM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MKC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MCD')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MCK')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MDT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MRK')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MET')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MTD')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MGM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MCHP')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MU')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MSFT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MAA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MHK')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TAP')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MDLZ')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MPWR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MNST')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MCO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MSI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MSCI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NDAQ')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NTAP')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NFLX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NWL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NEM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NWSA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NWS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NEE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NLSN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NKE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NSC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NTRS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NOC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NCLH')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NOV')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NRG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NUE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NVDA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NVR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NXPI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ORLY')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'OXY')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ODFL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'OMC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'OKE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ORCL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PCAR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PKG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PH')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PAYX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PAYC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PYPL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PENN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PNR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PBCT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PEP')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PKI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PRGO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PFE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PSX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PNW')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PXD')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PNC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'POOL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PPG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PPL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PFG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PGR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PLD')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PRU')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PEG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PSA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PHM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PVH')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'QRVO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'QCOM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'PWR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DGX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'RL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'RJF')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'O')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'REG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'REGN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'RF')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'RSG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'RMD')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'RHI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ROK')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ROL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ROP')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ROST')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'RCL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SPGI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CRM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SBAC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SLB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'STX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SEE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SRE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'NOW')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SHW')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SPG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SWKS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SNA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'LUV')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SWK')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SBUX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'STT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'STE')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SYK')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SIVB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SYF')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SNPS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'SYY')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TMUS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TROW')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TTWO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TGT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TEL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TDY')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TFX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TER')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TSLA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TXN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TXT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'BK')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'CLX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'COO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'HSY')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'MOS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TRV')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'DIS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TMO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TJX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TSCO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TDG')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TRMB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TWTR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TYL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'TSN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'USB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'UDR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ULTA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'UA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'UNP')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'UAL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'UPS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'URI')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'UNH')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'UHS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'UNM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'VLO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'VAR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'VTR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'VRSN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'VRSK')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'VZ')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 17) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'VRTX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'VFC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'V')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'VNO')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'VMC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'WRB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'WBA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'WMT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 23) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'WM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'WAT')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'WEC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'WFC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'WST')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'WDC')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'WU')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'WAB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'WRK')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 21) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'WY')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 22) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'WHR')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'WMB')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 4) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'WLTW')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'WYNN')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'XEL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 19) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'XLNX')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'XYL')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 15) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'YUM')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 18) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ZBRA')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 16) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ZBH')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ZION')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 20) ON CONFLICT DO NOTHING ;
INSERT INTO stocks.etf_stock (etf_ticker, stock_ticker) VALUES ('SPY', 'ZTS')ON CONFLICT DO NOTHING ;
INSERT INTO stocks.instrument_industry (ticker, industry_id) VALUES ('SPY', 2) ON CONFLICT DO NOTHING ;
commit;
